# ==============================================================================
# SonarQube Scanner Configuration
# ==============================================================================
sonar.projectKey=rabansdev-pixel_Cafeter-a
sonar.projectName=rabansdev-pixel
sonar.projectVersion=1.0.0
sonar.organization=rabansdev-pixel

# Rutas de código fuente y pruebas
sonar.sources=app
sonar.tests=tests

# Codificación y lenguajes
sonar.sourceEncoding=UTF-8
sonar.language=py

# Exclusiones de análisis estático
sonar.exclusions=app/static/vendor/**,**/__pycache__/**,**/*.pyc,app/static/img/**

# Reporte de Cobertura de Pruebas (generado por pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage-js/lcov.info

# Reporte de Linter (opcional)
sonar.python.xunit.reportPath=test-report.xml
